add_lunch_combo illusion_d2att-userdebug
add_lunch_combo illusion_d2mtr-userdebug
add_lunch_combo illusion_d2spr-userdebug
add_lunch_combo illusion_d2tmo-userdebug
add_lunch_combo illusion_d2usc-userdebug
add_lunch_combo illusion_d2vzw-userdebug
add_lunch_combo illusion_i9300-userdebug
add_lunch_combo illusion_jfltexx-userdebug
add_lunch_combo illusion_jflteatt-userdebug
add_lunch_combo illusion_jfltecan-userdebug
add_lunch_combo illusion_jfltespr-userdebug
add_lunch_combo illusion_jfltetmo-userdebug
add_lunch_combo illusion_jflteusc-userdebug
add_lunch_combo illusion_jfltevzw-userdebug
add_lunch_combo illusion_mako-userdebug
add_lunch_combo illusion_ville-userdebug
add_lunch_combo illusion_galaxysmtd-userdebug
add_lunch_combo illusion_n7000-userdebug
add_lunch_combo illusion_i9100-userdebug
add_lunch_combo illusion_n7100-userdebug



